# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='host_tag',
            field=models.ManyToManyField(to='cmdb.Host'),
        ),
    ]
