# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170331_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='server_info',
        ),
        migrations.AddField(
            model_name='host',
            name='disk',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
    ]
