# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
